[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app_updated:app --bind 0.0.0.0:7860"
healthcheckPath = "/keep-alive"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "7860"
